### ISSUE TITLE
Put the build instructions on two lines

### ISSUE THREAD

**Issue by BlackCapCoder** [olaven/arbeidskrav#1]
In `/V18_1/besvarelse/README.md` you write the two build commands on a single line. This might confuse people and render them unable to try the demo! I propose you stick them on two lines like so:

```bash
javac *
java Client
```

**Comment by olaven** [comment]
In retrospect, I agree. It was done in a hurry 👍

**Comment by BlackCapCoder** [comment]
But the deadline is like the 23rd :confused:

**Comment by olaven** [comment]
21st 😱 Hurry 🙀

**Comment by BlackCapCoder** [comment]
:fearful: https://github.com/BlackCapCoder/Meters
