### ISSUE TITLE
Why are you checking for an empty string?

### ISSUE THREAD

**Issue by BlackCapCoder** [olaven/arbeidskrav#5]
https://github.com/olaven/arbeidskrav/blob/7b7ba5952bfcde895f1f3f242956909ad89f9c27/V18_2/Question.java#L34-L41

You could argue that it makes sense to verify that the string is not null, but I would argument strongly against an empty string.
Firstly, unlike null an empty string will not crash your program, and there are tons of valid reasons why you might want one. 
Secondly, I think it is fairly safe to assume that the questions will not change after initialization, and if that is the case then the constructor is the only place where those setters are being used, so if a question is initialized with an empty string then the question will just be an empty string regardless!
Lastly; if questions indeed are immutable after initialization then the setters are entirely redundant altogether.

**Comment by olaven** [comment]
> it is fairly safe to assume that the questions will not change after initialization, and if that is the case then the constructor is the only place where those setters are being used, so if a question is initialized with an empty string then the question will just be an empty string regardless!

This is a good point 👍 I will remove the check. Thanks 🐩 

To your last point: Yes, it is redundant. I would argue that it is good to have setters anyways, for sake of consistency across multiple classes (Constructors, in this case) 🍨🔆

**Comment by BlackCapCoder** [comment]
> I would argue that it is good to have setters anyways, for sake of consistency across multiple classes

It doesn't actually matter in this case, but most languages has something called `function call overhead`. Calling a function actually has a cost attached to it, and in C# at least it is so bad that you can multiply your speed by in-lining a function in a tight loop.
As such it makes sense to inline short functions that are only used in a few places.

#### EDIT:
I looked it up, and it turns out that the JVM does in-lining at run-time if it ever becomes a problem, so you can just ignore the issue. One point to Java! :clap:
